/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { contractAddressList } from "../constants/contractAddress";
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    InspChain: {
      address: contractAddressList.InspChainAddress, //0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "_admin",
              type: "address",
            },
            {
              internalType: "address",
              name: "_inspector",
              type: "address",
            },
            {
              internalType: "string",
              name: "_inspectTarget",
              type: "string",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "approvedBy",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "inspectionIndex",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "comment",
              type: "string",
            },
            {
              indexed: false,
              internalType: "enum InspChain.JudgeState",
              name: "state",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "timestamp",
              type: "uint256",
            },
          ],
          name: "InspectionJudged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "submittedBy",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "inspectionType",
              type: "string",
            },
            {
              indexed: false,
              internalType: "string",
              name: "inspectionDetail",
              type: "string",
            },
            {
              indexed: false,
              internalType: "string",
              name: "statusMessage",
              type: "string",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "timestamp",
              type: "uint256",
            },
          ],
          name: "InspectionSubmitted",
          type: "event",
        },
        {
          inputs: [],
          name: "admin",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_index",
              type: "uint256",
            },
          ],
          name: "getInspection",
          outputs: [
            {
              internalType: "address",
              name: "inspector",
              type: "address",
            },
            {
              internalType: "string",
              name: "inspectionType",
              type: "string",
            },
            {
              internalType: "string",
              name: "inspectionDetails",
              type: "string",
            },
            {
              internalType: "string",
              name: "inspectionStatusMessage",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "timestamp",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "judgeTimestamp",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "judgeComment",
              type: "string",
            },
            {
              internalType: "enum InspChain.JudgeState",
              name: "state",
              type: "uint8",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getInspectionCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "inspectTarget",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "inspectionHistories",
          outputs: [
            {
              internalType: "address",
              name: "inspector",
              type: "address",
            },
            {
              internalType: "string",
              name: "inspectionType",
              type: "string",
            },
            {
              internalType: "string",
              name: "inspectionDetail",
              type: "string",
            },
            {
              internalType: "string",
              name: "inspectionStatusMessage",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "timestamp",
              type: "uint256",
            },
            {
              components: [
                {
                  internalType: "uint256",
                  name: "timestamp",
                  type: "uint256",
                },
                {
                  internalType: "string",
                  name: "comment",
                  type: "string",
                },
                {
                  internalType: "enum InspChain.JudgeState",
                  name: "state",
                  type: "uint8",
                },
              ],
              internalType: "struct InspChain.JudgeHistory",
              name: "judgeHistory",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "inspector",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_inspectionIndex",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "_comment",
              type: "string",
            },
            {
              internalType: "enum InspChain.JudgeState",
              name: "_state",
              type: "uint8",
            },
          ],
          name: "judgeInspection",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_inspectionType",
              type: "string",
            },
            {
              internalType: "string",
              name: "_detail",
              type: "string",
            },
            {
              internalType: "string",
              name: "_statusMessage",
              type: "string",
            },
          ],
          name: "submitInspection",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
    YourContract: {
      address: contractAddressList.YourContractAddress, //0x5FbDB2315678afecb367f032d93F642f64180aa3
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "_owner",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "greetingSetter",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "newGreeting",
              type: "string",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "premium",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "GreetingChange",
          type: "event",
        },
        {
          inputs: [],
          name: "greeting",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "premium",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_newGreeting",
              type: "string",
            },
          ],
          name: "setGreeting",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [],
          name: "totalCounter",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "userGreetingCounter",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "withdraw",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          stateMutability: "payable",
          type: "receive",
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
